[book]
authors = ["Oliver Killane"]
language = "en"
multilingual = false
src = "src"
title = "ADSD"
description = "Documentation for helping with ADSD"

[output.html]
mathjax-support = true
default-theme = "light"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/OliverKillane/ADSD/edit/main/docs/"
edit-url-template = "https://github.com/OliverKillane/ADSD/edit/main/docs/{path}"

[output.html.code.hidelines]
python = "~"

[output.html.playground]
editable = true
line-numbers = true